### ISSUE TITLE
Lang configuration issue

### ISSUE THREAD

**Issue by helios-ventures** [mayerbalintdev/GYM-One#2]
Encountering this language error 

'A nyelvi fájl nem található: C:\xampp\htdocs\gymone\trainers/../assets/lang/.json'

**Comment by mayerbalintdev** [comment]
The problem occurs because the .env file is not available. As I mentioned in Issue #1, the .env file is created by the GYM One Installer, which requires you to enter all the necessary settings via an interface. Because of this, you cannot load the language file, as it is read from the LANG_CODE=HU line.
